// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID                uuid.UUID
	OwnerID           uuid.NullUUID
	Filename          string
	FilePath          string
	FileSize          int64
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type FileAccessKey struct {
	ID         uuid.UUID
	FileID     uuid.NullUUID
	UserID     uuid.NullUUID
	WrappedKey string
	CreatedAt  sql.NullTime
}

type FileShare struct {
	ID               uuid.UUID
	FileID           uuid.NullUUID
	SharedWithUserID uuid.NullUUID
	WrappedKey       string
	CreatedAt        time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	RevokedAt sql.NullTime
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Username            string
	Email               string
	PasswordHash        string
	PublicKey           string
	PrivateKeyEncrypted string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
