// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	CreateRefreshTokenParams
	CreatedAt time.Time
	UpdatedAt time.Time
	RevokedAt *time.Time
}

type File struct {
	ID                uuid.UUID
	OwnerID           uuid.NullUUID
	Filename          string
	FilePath          string
	FileSize          int64
	EncryptedMetadata sql.NullString
	CurrentKeyVersion sql.NullInt32
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type User struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Username            string
	Email               string
	PasswordHash        string
	PublicKey           string
	PrivateKeyEncrypted string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
