// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	CreateRefreshTokenParams
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	
}

type User struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Username            string
	Email               string
	PasswordHash        string
	PublicKey           string
	PrivateKeyEncrypted string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}



